### PR TITLE
Added initial work on Refined Relocation compat

### PR DESCRIPTION
**Pull request by Dynious**
I started with adding compatibility with Refined Relocation. In this way all chests will be upgradable with the Refined Relocation in-world upgrade, but will not be able to be crafted in the Chest Builder or other recipes. The Sorting version will also not show up in the creative menu yet. I added 2 TODOs which are basically needed enhancements.

The compat is basically 100% functional, the Sorting versions of the chests work perfectly, so everything involving the RR API in done. Only thing left to do is letting users know the Sorting versions are available (by making them craftable and adding them to the creative menu).

### CODE REVIEW

**Comment by tattyseal** [comment]
I'll take a look when I get on my PC :+1: But looks alright, just have to make sure that it works! :D

**Comment by Dynious** [comment]
Any updates on this? 50% of the user interactions I have now are: "Why doesn't Compact Storage work with RR?" :P

**Comment by tattyseal** [comment]
The branches match up. Have you tested it to the point you think it is ok to go out to the public? If it is I will just merge it.

**Comment by Dynious** [comment]
Other than the issues listed in the original post, it works fine. This can be made public, but maybe it's a good idea to add the sorting version to the creative menu. Obviously a way to craft the block would be nice too, but without it users should still be able to use the sorting versions using to upgrades.

**Pull request merged**
